### ISSUE TITLE
Compatible with Ice and Fire: RLCraft Edition

### ISSUE THREAD

**Issue by al-wei** [strubium/TheOneSmeagle#10]
rlc has no display function.
So may not make display compatible.
Can you manually comply with rl?
![At least there is no display phase](https://github.com/user-attachments/assets/76d9f112-43d2-4719-8575-264fc1df89c0)

**Comment by strubium** [comment]
I am not quite sure what you mean. 

If English isn't your first language, you can always send your native and I can run it through a translator

**Comment by al-wei** [comment]
iaf 对top与hwyla有信息显示支持。
（比如显示龙的生长等级）
但是iaf rl没有支持/兼容。

你可以手动兼容iaf rl吗？

**Comment by strubium** [comment]
Ok, I understand now. Thank you.

The original Ice and Fire used TOP's API to display the extra information, it looks like Ice and Fire RLCraft Edition removed this. I just added support for mobs using MultiPartEntityPart (Like the Ender Dragon), but the RLCraft Devs will need to re-add support for displaying their custom info. I will make a issue. 


https://github.com/AlexModGuy/Ice_and_Fire/blob/1.12.2/src/main/java/com/github/alexthe666/iceandfire/compat/theoneprobe/DragonInfoProvider.java

**Comment by al-wei** [comment]
rlc 没有top, hwyla mod。
所以不需要制作mod支持/兼容。
所以我想 iaf rl 是不可能制作兼容的。
只能由top, hwyla支持 rl。

**Comment by strubium** [comment]
I spoke with Fonnymunkey; they said that they based Ice and Fire RLCraft Edition 1.7.1, which didn't have top or Hwyla support, and it hasn't been backported. They also said that they are open to compat requests, so I don't see why they wouldn't re-add it.

![image](https://github.com/user-attachments/assets/8c8c4ab1-1fbd-41cd-b24b-a1111ead4bf3)

**Comment by al-wei** [comment]
如上所述。

rlc没有tophwyla。
不需要制作。
因为如果使用rlc的玩家添加top。那么他们得不到显示功能。
所以可以保留rlc游戏难度。

rl团队的做法非常符合rlc。

**Comment by strubium** [comment]
Ok

**Comment by strubium** [comment]
@al-wei 
![image](https://github.com/user-attachments/assets/eefd5a6f-29ef-4939-99a0-22f455495093)

**Comment by al-wei** [comment]
Don't forget hwyla.
