### ISSUE TITLE
enhance

### ISSUE THREAD

**Issue by al-wei** [strubium/TheOneSmeagle#3]
I noticed that I couldn't view the entity ID, The laying time of chickens.
Will TOS have all the features?

Hwyla/Wawla/Waila Harvestability/jade/

**Comment by strubium** [comment]
I'm adding the chickens egg laying time to the Creative probe, would you like it to be shown with the regular probe? It would be controlled by a config option.

**Comment by al-wei** [comment]
> I'm adding the chickens egg laying time to the Creative probe, would you like it to be shown with the regular probe? It would be controlled by a config option.

Of course, it's best to be free to control.

**Comment by al-wei** [comment]
In addition, TOS lacks a lot of translation keys.
![image](https://github.com/user-attachments/assets/8648c77c-5821-4d44-999e-8440abb1bf49)

**Comment by strubium** [comment]
Fixed! thanks for the report! 

https://github.com/strubium/TheOneSmeagle/commit/48285e10780d58faff7a2046c9df0c60510b7d69

**Comment by al-wei** [comment]
> Fixed! thanks for the report!
> 
> [48285e1](https://github.com/strubium/TheOneSmeagle/commit/48285e10780d58faff7a2046c9df0c60510b7d69)

![image](https://github.com/user-attachments/assets/c7ba1e30-8254-4a8f-bcc5-0086cd956323)
Can TOS display modname?

**Comment by al-wei** [comment]
![image](https://github.com/user-attachments/assets/882fb109-5b08-4c72-a9a1-2d80ccf4d060)
