### ISSUE TITLE
Enhanced

### ISSUE THREAD

**Issue by al-wei** [strubium/TheOneSmeagle#4]
![image](https://github.com/user-attachments/assets/a57a95dd-32c0-47d6-b356-bfd87d5dd1f8)
I have an idea, add Baubles.
So you don't have to switch helmets.
There will be huge compatibility, modpack players can use more powerful helmets than diamond helmets.
Make the recipe more expensive to make it more challenging.

https://www.curseforge.com/minecraft/mc-mods/baubles
newfork
https://www.curseforge.com/minecraft/mc-mods/bubbles-a-baubles-fork
https://www.curseforge.com/minecraft/mc-mods/baublesex

**Comment by strubium** [comment]
![2024-10-11_11 42 00](https://github.com/user-attachments/assets/8112a278-811f-4c61-96ed-903ba5ddfb52)

This is already part of mod, it adds a bauble for the head slot.

**Comment by al-wei** [comment]
> ![2024-10-11_11 42 00](https://private-user-images.githubusercontent.com/113206902/375829332-8112a278-811f-4c61-96ed-903ba5ddfb52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTYzNzYsIm5iZiI6MTcyODcxNjA3NiwicGF0aCI6Ii8xMTMyMDY5MDIvMzc1ODI5MzMyLTgxMTJhMjc4LTgxMWYtNGM2MS05NmVkLTkwM2JhNWRkZmI1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNjU0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NGUwMzgxZmM0MzY2NjA5MGU2YjNlNDVmZWIwNWE1MGJkNGMyYThkNjUwNTdmNmUzNmUzZDk3ODgxYWQ5YmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gdlh8BmDIABRHlZiQwX8wLlKUGjjxyf8-ojjglqYE8Y)
> 
> This is already part of mod, it adds a bauble for the head slot.

Add Config Close helmet?
